spring:
  datasource:
    url: jdbc:h2:mem:sdw2003
    username: sdw2003
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enable: true
      path: /h2-console
      setting:
        trace: false
        web-allow-others: false
